# Generated by Django 4.2.1 on 2024-01-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_device_company_devicelog_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelog',
            name='is_returned',
            field=models.BooleanField(default=True),
        ),
    ]
