# Generated by Django 4.2.9 on 2024-01-26 22:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
